def run_util_tests():
    try:
        pass
    except Exception as e:
        print(e)
